export const slides = [
  {
    tag: "Ads (OOH Campaign)",
    marquee: "Stories on Street",
    image: "./Lab/work1.jpg",
    link: "View Project",
    links: "./index.html",
    year: "2025",
    type: "GO-KID Urban Bikes",
    alt: "project-1",
  },
  {
    tag: "Branding",
    marquee: "Essence No. 532-8",
    image: "./Lab/work2.jpg",
    link: "View Project",
    links: "./project.html",
    year: "2025",
    type: "Zara",
    alt: "project-2",
  },
  {
    tag: "Branding",
    marquee: "Golden Haze",
    image: "./Lab/work3.jpg",
    link: "View Project",
    links: "./index.html",
    year: "2024",
    type: "Sora Skincare",
    alt: "project-3",
  },
  {
    tag: "Photography",
    marquee: "Shape the Noise",
    image: "./Lab/img4.jpg",
    link: "View Project",
    links: "./index.html",
    year: "2024",
    type: "Ether Audio",
    alt: "project-4",
  },
];
